site_name: Libraries by Edward Jazzhands
site_description: Documentation for all libraries by Edward Jazzhands
site_author: Edward Jazzhands
site_url: https://edward-jazzhands.github.io/libraries/
theme: 
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - content.code.annotate
  palette:
    # Dark Mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

    # Light Mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

nav:
  - Rich-Pyfiglet: 
    - Guide: rich-pyfiglet/index.md
    - Reference: rich-pyfiglet/reference.md  
  - Textual-Pyfiglet:  
    - Guide: textual-pyfiglet/index.md   
    - Reference: textual-pyfiglet/reference.md  
  - Textual-SlideContainer: 
    - Guide: textual-slidecontainer/index.md
    - Reference: textual-slidecontainer/reference.md
  - Textual-Window:
    - Guide: textual-window/index.md
    - Reference: textual-window/reference.md
  - Textual-Color-O-Matic:
    - Guide: textual-coloromatic/index.md
    - Reference: textual-coloromatic/reference.md    

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.github.com/edward-jazzhands

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.snippets
  - pymdownx.superfences   
  - admonition
  - attr_list
  - md_in_html  
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers: 
        python:
          options:
            show_source: false

